// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ncvfs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class ListDirectoryRequestPro;
class ListDirectoryReplyPro;
class FileInfoPro;

// ===================================================================

class ListDirectoryRequestPro : public ::google::protobuf::Message {
 public:
  ListDirectoryRequestPro();
  virtual ~ListDirectoryRequestPro();
  
  ListDirectoryRequestPro(const ListDirectoryRequestPro& from);
  
  inline ListDirectoryRequestPro& operator=(const ListDirectoryRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListDirectoryRequestPro& default_instance();
  
  void Swap(ListDirectoryRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  ListDirectoryRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListDirectoryRequestPro& from);
  void MergeFrom(const ListDirectoryRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 osdId = 1;
  inline bool has_osdid() const;
  inline void clear_osdid();
  static const int kOsdIdFieldNumber = 1;
  inline ::google::protobuf::int32 osdid() const;
  inline void set_osdid(::google::protobuf::int32 value);
  
  // optional string directoryPath = 2;
  inline bool has_directorypath() const;
  inline void clear_directorypath();
  static const int kDirectoryPathFieldNumber = 2;
  inline const ::std::string& directorypath() const;
  inline void set_directorypath(const ::std::string& value);
  inline void set_directorypath(const char* value);
  inline void set_directorypath(const char* value, size_t size);
  inline ::std::string* mutable_directorypath();
  inline ::std::string* release_directorypath();
  
  // @@protoc_insertion_point(class_scope:ncvfs.ListDirectoryRequestPro)
 private:
  inline void set_has_osdid();
  inline void clear_has_osdid();
  inline void set_has_directorypath();
  inline void clear_has_directorypath();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* directorypath_;
  ::google::protobuf::int32 osdid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static ListDirectoryRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class ListDirectoryReplyPro : public ::google::protobuf::Message {
 public:
  ListDirectoryReplyPro();
  virtual ~ListDirectoryReplyPro();
  
  ListDirectoryReplyPro(const ListDirectoryReplyPro& from);
  
  inline ListDirectoryReplyPro& operator=(const ListDirectoryReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListDirectoryReplyPro& default_instance();
  
  void Swap(ListDirectoryReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  ListDirectoryReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListDirectoryReplyPro& from);
  void MergeFrom(const ListDirectoryReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ncvfs.FileInfoPro fileInfoPro = 1;
  inline int fileinfopro_size() const;
  inline void clear_fileinfopro();
  static const int kFileInfoProFieldNumber = 1;
  inline const ::ncvfs::FileInfoPro& fileinfopro(int index) const;
  inline ::ncvfs::FileInfoPro* mutable_fileinfopro(int index);
  inline ::ncvfs::FileInfoPro* add_fileinfopro();
  inline const ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >&
      fileinfopro() const;
  inline ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >*
      mutable_fileinfopro();
  
  // @@protoc_insertion_point(class_scope:ncvfs.ListDirectoryReplyPro)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro > fileinfopro_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static ListDirectoryReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class FileInfoPro : public ::google::protobuf::Message {
 public:
  FileInfoPro();
  virtual ~FileInfoPro();
  
  FileInfoPro(const FileInfoPro& from);
  
  inline FileInfoPro& operator=(const FileInfoPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FileInfoPro& default_instance();
  
  void Swap(FileInfoPro* other);
  
  // implements Message ----------------------------------------------
  
  FileInfoPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileInfoPro& from);
  void MergeFrom(const FileInfoPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed32 fileId = 1;
  inline bool has_fileid() const;
  inline void clear_fileid();
  static const int kFileIdFieldNumber = 1;
  inline ::google::protobuf::uint32 fileid() const;
  inline void set_fileid(::google::protobuf::uint32 value);
  
  // optional fixed64 fileSize = 2;
  inline bool has_filesize() const;
  inline void clear_filesize();
  static const int kFileSizeFieldNumber = 2;
  inline ::google::protobuf::uint64 filesize() const;
  inline void set_filesize(::google::protobuf::uint64 value);
  
  // optional string fileName = 3;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFileNameFieldNumber = 3;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  
  // @@protoc_insertion_point(class_scope:ncvfs.FileInfoPro)
 private:
  inline void set_has_fileid();
  inline void clear_has_fileid();
  inline void set_has_filesize();
  inline void clear_has_filesize();
  inline void set_has_filename();
  inline void clear_has_filename();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 filesize_;
  ::std::string* filename_;
  ::google::protobuf::uint32 fileid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static FileInfoPro* default_instance_;
};
// ===================================================================


// ===================================================================

// ListDirectoryRequestPro

// optional int32 osdId = 1;
inline bool ListDirectoryRequestPro::has_osdid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ListDirectoryRequestPro::set_has_osdid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ListDirectoryRequestPro::clear_has_osdid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ListDirectoryRequestPro::clear_osdid() {
  osdid_ = 0;
  clear_has_osdid();
}
inline ::google::protobuf::int32 ListDirectoryRequestPro::osdid() const {
  return osdid_;
}
inline void ListDirectoryRequestPro::set_osdid(::google::protobuf::int32 value) {
  set_has_osdid();
  osdid_ = value;
}

// optional string directoryPath = 2;
inline bool ListDirectoryRequestPro::has_directorypath() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ListDirectoryRequestPro::set_has_directorypath() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ListDirectoryRequestPro::clear_has_directorypath() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ListDirectoryRequestPro::clear_directorypath() {
  if (directorypath_ != &::google::protobuf::internal::kEmptyString) {
    directorypath_->clear();
  }
  clear_has_directorypath();
}
inline const ::std::string& ListDirectoryRequestPro::directorypath() const {
  return *directorypath_;
}
inline void ListDirectoryRequestPro::set_directorypath(const ::std::string& value) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(value);
}
inline void ListDirectoryRequestPro::set_directorypath(const char* value) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(value);
}
inline void ListDirectoryRequestPro::set_directorypath(const char* value, size_t size) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ListDirectoryRequestPro::mutable_directorypath() {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  return directorypath_;
}
inline ::std::string* ListDirectoryRequestPro::release_directorypath() {
  clear_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = directorypath_;
    directorypath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// ListDirectoryReplyPro

// repeated .ncvfs.FileInfoPro fileInfoPro = 1;
inline int ListDirectoryReplyPro::fileinfopro_size() const {
  return fileinfopro_.size();
}
inline void ListDirectoryReplyPro::clear_fileinfopro() {
  fileinfopro_.Clear();
}
inline const ::ncvfs::FileInfoPro& ListDirectoryReplyPro::fileinfopro(int index) const {
  return fileinfopro_.Get(index);
}
inline ::ncvfs::FileInfoPro* ListDirectoryReplyPro::mutable_fileinfopro(int index) {
  return fileinfopro_.Mutable(index);
}
inline ::ncvfs::FileInfoPro* ListDirectoryReplyPro::add_fileinfopro() {
  return fileinfopro_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >&
ListDirectoryReplyPro::fileinfopro() const {
  return fileinfopro_;
}
inline ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >*
ListDirectoryReplyPro::mutable_fileinfopro() {
  return &fileinfopro_;
}

// -------------------------------------------------------------------

// FileInfoPro

// optional fixed32 fileId = 1;
inline bool FileInfoPro::has_fileid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FileInfoPro::set_has_fileid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FileInfoPro::clear_has_fileid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FileInfoPro::clear_fileid() {
  fileid_ = 0u;
  clear_has_fileid();
}
inline ::google::protobuf::uint32 FileInfoPro::fileid() const {
  return fileid_;
}
inline void FileInfoPro::set_fileid(::google::protobuf::uint32 value) {
  set_has_fileid();
  fileid_ = value;
}

// optional fixed64 fileSize = 2;
inline bool FileInfoPro::has_filesize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FileInfoPro::set_has_filesize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FileInfoPro::clear_has_filesize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FileInfoPro::clear_filesize() {
  filesize_ = GOOGLE_ULONGLONG(0);
  clear_has_filesize();
}
inline ::google::protobuf::uint64 FileInfoPro::filesize() const {
  return filesize_;
}
inline void FileInfoPro::set_filesize(::google::protobuf::uint64 value) {
  set_has_filesize();
  filesize_ = value;
}

// optional string fileName = 3;
inline bool FileInfoPro::has_filename() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FileInfoPro::set_has_filename() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FileInfoPro::clear_has_filename() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FileInfoPro::clear_filename() {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& FileInfoPro::filename() const {
  return *filename_;
}
inline void FileInfoPro::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void FileInfoPro::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void FileInfoPro::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FileInfoPro::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* FileInfoPro::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ncvfs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
