// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ncvfs {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class ListDirectoryRequestPro;
class UploadFileRequestPro;
class ListDirectoryReplyPro;
class FileInfoPro;
class UploadFileReplyPro;
class PutObjectInitRequestPro;
class ObjectDataPro;
class PutObjectEndRequestPro;
class PutObjectInitReplyPro;
class PutObjectEndReplyPro;
class PutSegmentInitRequestPro;
class SegmentDataPro;
class PutSegmentEndRequestPro;
class PutSegmentInitReplyPro;
class PutSegmentEndReplyPro;

// ===================================================================

class ListDirectoryRequestPro : public ::google::protobuf::Message {
 public:
  ListDirectoryRequestPro();
  virtual ~ListDirectoryRequestPro();
  
  ListDirectoryRequestPro(const ListDirectoryRequestPro& from);
  
  inline ListDirectoryRequestPro& operator=(const ListDirectoryRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListDirectoryRequestPro& default_instance();
  
  void Swap(ListDirectoryRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  ListDirectoryRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListDirectoryRequestPro& from);
  void MergeFrom(const ListDirectoryRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 osdId = 1;
  inline bool has_osdid() const;
  inline void clear_osdid();
  static const int kOsdIdFieldNumber = 1;
  inline ::google::protobuf::int32 osdid() const;
  inline void set_osdid(::google::protobuf::int32 value);
  
  // optional string directoryPath = 2;
  inline bool has_directorypath() const;
  inline void clear_directorypath();
  static const int kDirectoryPathFieldNumber = 2;
  inline const ::std::string& directorypath() const;
  inline void set_directorypath(const ::std::string& value);
  inline void set_directorypath(const char* value);
  inline void set_directorypath(const char* value, size_t size);
  inline ::std::string* mutable_directorypath();
  inline ::std::string* release_directorypath();
  
  // @@protoc_insertion_point(class_scope:ncvfs.ListDirectoryRequestPro)
 private:
  inline void set_has_osdid();
  inline void clear_has_osdid();
  inline void set_has_directorypath();
  inline void clear_has_directorypath();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* directorypath_;
  ::google::protobuf::int32 osdid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static ListDirectoryRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class UploadFileRequestPro : public ::google::protobuf::Message {
 public:
  UploadFileRequestPro();
  virtual ~UploadFileRequestPro();
  
  UploadFileRequestPro(const UploadFileRequestPro& from);
  
  inline UploadFileRequestPro& operator=(const UploadFileRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UploadFileRequestPro& default_instance();
  
  void Swap(UploadFileRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  UploadFileRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UploadFileRequestPro& from);
  void MergeFrom(const UploadFileRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string fileName = 1;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFileNameFieldNumber = 1;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  
  // required fixed32 numOfObj = 2;
  inline bool has_numofobj() const;
  inline void clear_numofobj();
  static const int kNumOfObjFieldNumber = 2;
  inline ::google::protobuf::uint32 numofobj() const;
  inline void set_numofobj(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.UploadFileRequestPro)
 private:
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_numofobj();
  inline void clear_has_numofobj();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* filename_;
  ::google::protobuf::uint32 numofobj_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static UploadFileRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class ListDirectoryReplyPro : public ::google::protobuf::Message {
 public:
  ListDirectoryReplyPro();
  virtual ~ListDirectoryReplyPro();
  
  ListDirectoryReplyPro(const ListDirectoryReplyPro& from);
  
  inline ListDirectoryReplyPro& operator=(const ListDirectoryReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ListDirectoryReplyPro& default_instance();
  
  void Swap(ListDirectoryReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  ListDirectoryReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListDirectoryReplyPro& from);
  void MergeFrom(const ListDirectoryReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ncvfs.FileInfoPro fileInfoPro = 1;
  inline int fileinfopro_size() const;
  inline void clear_fileinfopro();
  static const int kFileInfoProFieldNumber = 1;
  inline const ::ncvfs::FileInfoPro& fileinfopro(int index) const;
  inline ::ncvfs::FileInfoPro* mutable_fileinfopro(int index);
  inline ::ncvfs::FileInfoPro* add_fileinfopro();
  inline const ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >&
      fileinfopro() const;
  inline ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >*
      mutable_fileinfopro();
  
  // @@protoc_insertion_point(class_scope:ncvfs.ListDirectoryReplyPro)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro > fileinfopro_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static ListDirectoryReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class FileInfoPro : public ::google::protobuf::Message {
 public:
  FileInfoPro();
  virtual ~FileInfoPro();
  
  FileInfoPro(const FileInfoPro& from);
  
  inline FileInfoPro& operator=(const FileInfoPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const FileInfoPro& default_instance();
  
  void Swap(FileInfoPro* other);
  
  // implements Message ----------------------------------------------
  
  FileInfoPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileInfoPro& from);
  void MergeFrom(const FileInfoPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed32 fileId = 1;
  inline bool has_fileid() const;
  inline void clear_fileid();
  static const int kFileIdFieldNumber = 1;
  inline ::google::protobuf::uint32 fileid() const;
  inline void set_fileid(::google::protobuf::uint32 value);
  
  // optional fixed64 fileSize = 2;
  inline bool has_filesize() const;
  inline void clear_filesize();
  static const int kFileSizeFieldNumber = 2;
  inline ::google::protobuf::uint64 filesize() const;
  inline void set_filesize(::google::protobuf::uint64 value);
  
  // optional string fileName = 3;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFileNameFieldNumber = 3;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  
  // @@protoc_insertion_point(class_scope:ncvfs.FileInfoPro)
 private:
  inline void set_has_fileid();
  inline void clear_has_fileid();
  inline void set_has_filesize();
  inline void clear_has_filesize();
  inline void set_has_filename();
  inline void clear_has_filename();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 filesize_;
  ::std::string* filename_;
  ::google::protobuf::uint32 fileid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static FileInfoPro* default_instance_;
};
// -------------------------------------------------------------------

class UploadFileReplyPro : public ::google::protobuf::Message {
 public:
  UploadFileReplyPro();
  virtual ~UploadFileReplyPro();
  
  UploadFileReplyPro(const UploadFileReplyPro& from);
  
  inline UploadFileReplyPro& operator=(const UploadFileReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const UploadFileReplyPro& default_instance();
  
  void Swap(UploadFileReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  UploadFileReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UploadFileReplyPro& from);
  void MergeFrom(const UploadFileReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required fixed32 fileId = 1;
  inline bool has_fileid() const;
  inline void clear_fileid();
  static const int kFileIdFieldNumber = 1;
  inline ::google::protobuf::uint32 fileid() const;
  inline void set_fileid(::google::protobuf::uint32 value);
  
  // required fixed32 numOfObj = 2;
  inline bool has_numofobj() const;
  inline void clear_numofobj();
  static const int kNumOfObjFieldNumber = 2;
  inline ::google::protobuf::uint32 numofobj() const;
  inline void set_numofobj(::google::protobuf::uint32 value);
  
  // repeated fixed64 objectIdList = 3;
  inline int objectidlist_size() const;
  inline void clear_objectidlist();
  static const int kObjectIdListFieldNumber = 3;
  inline ::google::protobuf::uint64 objectidlist(int index) const;
  inline void set_objectidlist(int index, ::google::protobuf::uint64 value);
  inline void add_objectidlist(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      objectidlist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_objectidlist();
  
  // repeated fixed32 primaryList = 4;
  inline int primarylist_size() const;
  inline void clear_primarylist();
  static const int kPrimaryListFieldNumber = 4;
  inline ::google::protobuf::uint32 primarylist(int index) const;
  inline void set_primarylist(int index, ::google::protobuf::uint32 value);
  inline void add_primarylist(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      primarylist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_primarylist();
  
  // @@protoc_insertion_point(class_scope:ncvfs.UploadFileReplyPro)
 private:
  inline void set_has_fileid();
  inline void clear_has_fileid();
  inline void set_has_numofobj();
  inline void clear_has_numofobj();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 fileid_;
  ::google::protobuf::uint32 numofobj_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > objectidlist_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > primarylist_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static UploadFileReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class PutObjectInitRequestPro : public ::google::protobuf::Message {
 public:
  PutObjectInitRequestPro();
  virtual ~PutObjectInitRequestPro();
  
  PutObjectInitRequestPro(const PutObjectInitRequestPro& from);
  
  inline PutObjectInitRequestPro& operator=(const PutObjectInitRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutObjectInitRequestPro& default_instance();
  
  void Swap(PutObjectInitRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  PutObjectInitRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutObjectInitRequestPro& from);
  void MergeFrom(const PutObjectInitRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 objectSize = 2;
  inline bool has_objectsize() const;
  inline void clear_objectsize();
  static const int kObjectSizeFieldNumber = 2;
  inline ::google::protobuf::uint32 objectsize() const;
  inline void set_objectsize(::google::protobuf::uint32 value);
  
  // optional fixed32 chunkCount = 3;
  inline bool has_chunkcount() const;
  inline void clear_chunkcount();
  static const int kChunkCountFieldNumber = 3;
  inline ::google::protobuf::uint32 chunkcount() const;
  inline void set_chunkcount(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutObjectInitRequestPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_objectsize();
  inline void clear_has_objectsize();
  inline void set_has_chunkcount();
  inline void clear_has_chunkcount();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint32 objectsize_;
  ::google::protobuf::uint32 chunkcount_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutObjectInitRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class ObjectDataPro : public ::google::protobuf::Message {
 public:
  ObjectDataPro();
  virtual ~ObjectDataPro();
  
  ObjectDataPro(const ObjectDataPro& from);
  
  inline ObjectDataPro& operator=(const ObjectDataPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectDataPro& default_instance();
  
  void Swap(ObjectDataPro* other);
  
  // implements Message ----------------------------------------------
  
  ObjectDataPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectDataPro& from);
  void MergeFrom(const ObjectDataPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed64 offset = 2;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 2;
  inline ::google::protobuf::uint64 offset() const;
  inline void set_offset(::google::protobuf::uint64 value);
  
  // optional fixed32 length = 3;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 3;
  inline ::google::protobuf::uint32 length() const;
  inline void set_length(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.ObjectDataPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_length();
  inline void clear_has_length();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint64 offset_;
  ::google::protobuf::uint32 length_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static ObjectDataPro* default_instance_;
};
// -------------------------------------------------------------------

class PutObjectEndRequestPro : public ::google::protobuf::Message {
 public:
  PutObjectEndRequestPro();
  virtual ~PutObjectEndRequestPro();
  
  PutObjectEndRequestPro(const PutObjectEndRequestPro& from);
  
  inline PutObjectEndRequestPro& operator=(const PutObjectEndRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutObjectEndRequestPro& default_instance();
  
  void Swap(PutObjectEndRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  PutObjectEndRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutObjectEndRequestPro& from);
  void MergeFrom(const PutObjectEndRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutObjectEndRequestPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutObjectEndRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class PutObjectInitReplyPro : public ::google::protobuf::Message {
 public:
  PutObjectInitReplyPro();
  virtual ~PutObjectInitReplyPro();
  
  PutObjectInitReplyPro(const PutObjectInitReplyPro& from);
  
  inline PutObjectInitReplyPro& operator=(const PutObjectInitReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutObjectInitReplyPro& default_instance();
  
  void Swap(PutObjectInitReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  PutObjectInitReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutObjectInitReplyPro& from);
  void MergeFrom(const PutObjectInitReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutObjectInitReplyPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutObjectInitReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class PutObjectEndReplyPro : public ::google::protobuf::Message {
 public:
  PutObjectEndReplyPro();
  virtual ~PutObjectEndReplyPro();
  
  PutObjectEndReplyPro(const PutObjectEndReplyPro& from);
  
  inline PutObjectEndReplyPro& operator=(const PutObjectEndReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutObjectEndReplyPro& default_instance();
  
  void Swap(PutObjectEndReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  PutObjectEndReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutObjectEndReplyPro& from);
  void MergeFrom(const PutObjectEndReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutObjectEndReplyPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutObjectEndReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class PutSegmentInitRequestPro : public ::google::protobuf::Message {
 public:
  PutSegmentInitRequestPro();
  virtual ~PutSegmentInitRequestPro();
  
  PutSegmentInitRequestPro(const PutSegmentInitRequestPro& from);
  
  inline PutSegmentInitRequestPro& operator=(const PutSegmentInitRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutSegmentInitRequestPro& default_instance();
  
  void Swap(PutSegmentInitRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  PutSegmentInitRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutSegmentInitRequestPro& from);
  void MergeFrom(const PutSegmentInitRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 segmentId = 2;
  inline bool has_segmentid() const;
  inline void clear_segmentid();
  static const int kSegmentIdFieldNumber = 2;
  inline ::google::protobuf::uint32 segmentid() const;
  inline void set_segmentid(::google::protobuf::uint32 value);
  
  // optional fixed32 segmentSize = 3;
  inline bool has_segmentsize() const;
  inline void clear_segmentsize();
  static const int kSegmentSizeFieldNumber = 3;
  inline ::google::protobuf::uint32 segmentsize() const;
  inline void set_segmentsize(::google::protobuf::uint32 value);
  
  // optional fixed32 chunkCount = 4;
  inline bool has_chunkcount() const;
  inline void clear_chunkcount();
  static const int kChunkCountFieldNumber = 4;
  inline ::google::protobuf::uint32 chunkcount() const;
  inline void set_chunkcount(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutSegmentInitRequestPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_segmentid();
  inline void clear_has_segmentid();
  inline void set_has_segmentsize();
  inline void clear_has_segmentsize();
  inline void set_has_chunkcount();
  inline void clear_has_chunkcount();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint32 segmentid_;
  ::google::protobuf::uint32 segmentsize_;
  ::google::protobuf::uint32 chunkcount_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutSegmentInitRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class SegmentDataPro : public ::google::protobuf::Message {
 public:
  SegmentDataPro();
  virtual ~SegmentDataPro();
  
  SegmentDataPro(const SegmentDataPro& from);
  
  inline SegmentDataPro& operator=(const SegmentDataPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const SegmentDataPro& default_instance();
  
  void Swap(SegmentDataPro* other);
  
  // implements Message ----------------------------------------------
  
  SegmentDataPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SegmentDataPro& from);
  void MergeFrom(const SegmentDataPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 segmentId = 2;
  inline bool has_segmentid() const;
  inline void clear_segmentid();
  static const int kSegmentIdFieldNumber = 2;
  inline ::google::protobuf::uint32 segmentid() const;
  inline void set_segmentid(::google::protobuf::uint32 value);
  
  // optional fixed64 offset = 3;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 3;
  inline ::google::protobuf::uint64 offset() const;
  inline void set_offset(::google::protobuf::uint64 value);
  
  // optional fixed32 length = 4;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 4;
  inline ::google::protobuf::uint32 length() const;
  inline void set_length(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.SegmentDataPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_segmentid();
  inline void clear_has_segmentid();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_length();
  inline void clear_has_length();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint64 offset_;
  ::google::protobuf::uint32 segmentid_;
  ::google::protobuf::uint32 length_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static SegmentDataPro* default_instance_;
};
// -------------------------------------------------------------------

class PutSegmentEndRequestPro : public ::google::protobuf::Message {
 public:
  PutSegmentEndRequestPro();
  virtual ~PutSegmentEndRequestPro();
  
  PutSegmentEndRequestPro(const PutSegmentEndRequestPro& from);
  
  inline PutSegmentEndRequestPro& operator=(const PutSegmentEndRequestPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutSegmentEndRequestPro& default_instance();
  
  void Swap(PutSegmentEndRequestPro* other);
  
  // implements Message ----------------------------------------------
  
  PutSegmentEndRequestPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutSegmentEndRequestPro& from);
  void MergeFrom(const PutSegmentEndRequestPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 segmentId = 2;
  inline bool has_segmentid() const;
  inline void clear_segmentid();
  static const int kSegmentIdFieldNumber = 2;
  inline ::google::protobuf::uint32 segmentid() const;
  inline void set_segmentid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutSegmentEndRequestPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_segmentid();
  inline void clear_has_segmentid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint32 segmentid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutSegmentEndRequestPro* default_instance_;
};
// -------------------------------------------------------------------

class PutSegmentInitReplyPro : public ::google::protobuf::Message {
 public:
  PutSegmentInitReplyPro();
  virtual ~PutSegmentInitReplyPro();
  
  PutSegmentInitReplyPro(const PutSegmentInitReplyPro& from);
  
  inline PutSegmentInitReplyPro& operator=(const PutSegmentInitReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutSegmentInitReplyPro& default_instance();
  
  void Swap(PutSegmentInitReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  PutSegmentInitReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutSegmentInitReplyPro& from);
  void MergeFrom(const PutSegmentInitReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 segmentId = 2;
  inline bool has_segmentid() const;
  inline void clear_segmentid();
  static const int kSegmentIdFieldNumber = 2;
  inline ::google::protobuf::uint32 segmentid() const;
  inline void set_segmentid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutSegmentInitReplyPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_segmentid();
  inline void clear_has_segmentid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint32 segmentid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutSegmentInitReplyPro* default_instance_;
};
// -------------------------------------------------------------------

class PutSegmentEndReplyPro : public ::google::protobuf::Message {
 public:
  PutSegmentEndReplyPro();
  virtual ~PutSegmentEndReplyPro();
  
  PutSegmentEndReplyPro(const PutSegmentEndReplyPro& from);
  
  inline PutSegmentEndReplyPro& operator=(const PutSegmentEndReplyPro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PutSegmentEndReplyPro& default_instance();
  
  void Swap(PutSegmentEndReplyPro* other);
  
  // implements Message ----------------------------------------------
  
  PutSegmentEndReplyPro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PutSegmentEndReplyPro& from);
  void MergeFrom(const PutSegmentEndReplyPro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional fixed64 objectId = 1;
  inline bool has_objectid() const;
  inline void clear_objectid();
  static const int kObjectIdFieldNumber = 1;
  inline ::google::protobuf::uint64 objectid() const;
  inline void set_objectid(::google::protobuf::uint64 value);
  
  // optional fixed32 segmentId = 2;
  inline bool has_segmentid() const;
  inline void clear_segmentid();
  static const int kSegmentIdFieldNumber = 2;
  inline ::google::protobuf::uint32 segmentid() const;
  inline void set_segmentid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ncvfs.PutSegmentEndReplyPro)
 private:
  inline void set_has_objectid();
  inline void clear_has_objectid();
  inline void set_has_segmentid();
  inline void clear_has_segmentid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::uint32 segmentid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();
  
  void InitAsDefaultInstance();
  static PutSegmentEndReplyPro* default_instance_;
};
// ===================================================================


// ===================================================================

// ListDirectoryRequestPro

// optional int32 osdId = 1;
inline bool ListDirectoryRequestPro::has_osdid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ListDirectoryRequestPro::set_has_osdid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ListDirectoryRequestPro::clear_has_osdid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ListDirectoryRequestPro::clear_osdid() {
  osdid_ = 0;
  clear_has_osdid();
}
inline ::google::protobuf::int32 ListDirectoryRequestPro::osdid() const {
  return osdid_;
}
inline void ListDirectoryRequestPro::set_osdid(::google::protobuf::int32 value) {
  set_has_osdid();
  osdid_ = value;
}

// optional string directoryPath = 2;
inline bool ListDirectoryRequestPro::has_directorypath() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ListDirectoryRequestPro::set_has_directorypath() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ListDirectoryRequestPro::clear_has_directorypath() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ListDirectoryRequestPro::clear_directorypath() {
  if (directorypath_ != &::google::protobuf::internal::kEmptyString) {
    directorypath_->clear();
  }
  clear_has_directorypath();
}
inline const ::std::string& ListDirectoryRequestPro::directorypath() const {
  return *directorypath_;
}
inline void ListDirectoryRequestPro::set_directorypath(const ::std::string& value) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(value);
}
inline void ListDirectoryRequestPro::set_directorypath(const char* value) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(value);
}
inline void ListDirectoryRequestPro::set_directorypath(const char* value, size_t size) {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  directorypath_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ListDirectoryRequestPro::mutable_directorypath() {
  set_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    directorypath_ = new ::std::string;
  }
  return directorypath_;
}
inline ::std::string* ListDirectoryRequestPro::release_directorypath() {
  clear_has_directorypath();
  if (directorypath_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = directorypath_;
    directorypath_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// UploadFileRequestPro

// required string fileName = 1;
inline bool UploadFileRequestPro::has_filename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UploadFileRequestPro::set_has_filename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UploadFileRequestPro::clear_has_filename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UploadFileRequestPro::clear_filename() {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& UploadFileRequestPro::filename() const {
  return *filename_;
}
inline void UploadFileRequestPro::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void UploadFileRequestPro::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void UploadFileRequestPro::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* UploadFileRequestPro::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* UploadFileRequestPro::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required fixed32 numOfObj = 2;
inline bool UploadFileRequestPro::has_numofobj() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UploadFileRequestPro::set_has_numofobj() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UploadFileRequestPro::clear_has_numofobj() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UploadFileRequestPro::clear_numofobj() {
  numofobj_ = 0u;
  clear_has_numofobj();
}
inline ::google::protobuf::uint32 UploadFileRequestPro::numofobj() const {
  return numofobj_;
}
inline void UploadFileRequestPro::set_numofobj(::google::protobuf::uint32 value) {
  set_has_numofobj();
  numofobj_ = value;
}

// -------------------------------------------------------------------

// ListDirectoryReplyPro

// repeated .ncvfs.FileInfoPro fileInfoPro = 1;
inline int ListDirectoryReplyPro::fileinfopro_size() const {
  return fileinfopro_.size();
}
inline void ListDirectoryReplyPro::clear_fileinfopro() {
  fileinfopro_.Clear();
}
inline const ::ncvfs::FileInfoPro& ListDirectoryReplyPro::fileinfopro(int index) const {
  return fileinfopro_.Get(index);
}
inline ::ncvfs::FileInfoPro* ListDirectoryReplyPro::mutable_fileinfopro(int index) {
  return fileinfopro_.Mutable(index);
}
inline ::ncvfs::FileInfoPro* ListDirectoryReplyPro::add_fileinfopro() {
  return fileinfopro_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >&
ListDirectoryReplyPro::fileinfopro() const {
  return fileinfopro_;
}
inline ::google::protobuf::RepeatedPtrField< ::ncvfs::FileInfoPro >*
ListDirectoryReplyPro::mutable_fileinfopro() {
  return &fileinfopro_;
}

// -------------------------------------------------------------------

// FileInfoPro

// optional fixed32 fileId = 1;
inline bool FileInfoPro::has_fileid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FileInfoPro::set_has_fileid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FileInfoPro::clear_has_fileid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FileInfoPro::clear_fileid() {
  fileid_ = 0u;
  clear_has_fileid();
}
inline ::google::protobuf::uint32 FileInfoPro::fileid() const {
  return fileid_;
}
inline void FileInfoPro::set_fileid(::google::protobuf::uint32 value) {
  set_has_fileid();
  fileid_ = value;
}

// optional fixed64 fileSize = 2;
inline bool FileInfoPro::has_filesize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void FileInfoPro::set_has_filesize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void FileInfoPro::clear_has_filesize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void FileInfoPro::clear_filesize() {
  filesize_ = GOOGLE_ULONGLONG(0);
  clear_has_filesize();
}
inline ::google::protobuf::uint64 FileInfoPro::filesize() const {
  return filesize_;
}
inline void FileInfoPro::set_filesize(::google::protobuf::uint64 value) {
  set_has_filesize();
  filesize_ = value;
}

// optional string fileName = 3;
inline bool FileInfoPro::has_filename() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void FileInfoPro::set_has_filename() {
  _has_bits_[0] |= 0x00000004u;
}
inline void FileInfoPro::clear_has_filename() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void FileInfoPro::clear_filename() {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& FileInfoPro::filename() const {
  return *filename_;
}
inline void FileInfoPro::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void FileInfoPro::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void FileInfoPro::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* FileInfoPro::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* FileInfoPro::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// UploadFileReplyPro

// required fixed32 fileId = 1;
inline bool UploadFileReplyPro::has_fileid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UploadFileReplyPro::set_has_fileid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UploadFileReplyPro::clear_has_fileid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UploadFileReplyPro::clear_fileid() {
  fileid_ = 0u;
  clear_has_fileid();
}
inline ::google::protobuf::uint32 UploadFileReplyPro::fileid() const {
  return fileid_;
}
inline void UploadFileReplyPro::set_fileid(::google::protobuf::uint32 value) {
  set_has_fileid();
  fileid_ = value;
}

// required fixed32 numOfObj = 2;
inline bool UploadFileReplyPro::has_numofobj() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UploadFileReplyPro::set_has_numofobj() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UploadFileReplyPro::clear_has_numofobj() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UploadFileReplyPro::clear_numofobj() {
  numofobj_ = 0u;
  clear_has_numofobj();
}
inline ::google::protobuf::uint32 UploadFileReplyPro::numofobj() const {
  return numofobj_;
}
inline void UploadFileReplyPro::set_numofobj(::google::protobuf::uint32 value) {
  set_has_numofobj();
  numofobj_ = value;
}

// repeated fixed64 objectIdList = 3;
inline int UploadFileReplyPro::objectidlist_size() const {
  return objectidlist_.size();
}
inline void UploadFileReplyPro::clear_objectidlist() {
  objectidlist_.Clear();
}
inline ::google::protobuf::uint64 UploadFileReplyPro::objectidlist(int index) const {
  return objectidlist_.Get(index);
}
inline void UploadFileReplyPro::set_objectidlist(int index, ::google::protobuf::uint64 value) {
  objectidlist_.Set(index, value);
}
inline void UploadFileReplyPro::add_objectidlist(::google::protobuf::uint64 value) {
  objectidlist_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
UploadFileReplyPro::objectidlist() const {
  return objectidlist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
UploadFileReplyPro::mutable_objectidlist() {
  return &objectidlist_;
}

// repeated fixed32 primaryList = 4;
inline int UploadFileReplyPro::primarylist_size() const {
  return primarylist_.size();
}
inline void UploadFileReplyPro::clear_primarylist() {
  primarylist_.Clear();
}
inline ::google::protobuf::uint32 UploadFileReplyPro::primarylist(int index) const {
  return primarylist_.Get(index);
}
inline void UploadFileReplyPro::set_primarylist(int index, ::google::protobuf::uint32 value) {
  primarylist_.Set(index, value);
}
inline void UploadFileReplyPro::add_primarylist(::google::protobuf::uint32 value) {
  primarylist_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
UploadFileReplyPro::primarylist() const {
  return primarylist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
UploadFileReplyPro::mutable_primarylist() {
  return &primarylist_;
}

// -------------------------------------------------------------------

// PutObjectInitRequestPro

// optional fixed64 objectId = 1;
inline bool PutObjectInitRequestPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutObjectInitRequestPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutObjectInitRequestPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutObjectInitRequestPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutObjectInitRequestPro::objectid() const {
  return objectid_;
}
inline void PutObjectInitRequestPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 objectSize = 2;
inline bool PutObjectInitRequestPro::has_objectsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutObjectInitRequestPro::set_has_objectsize() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutObjectInitRequestPro::clear_has_objectsize() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutObjectInitRequestPro::clear_objectsize() {
  objectsize_ = 0u;
  clear_has_objectsize();
}
inline ::google::protobuf::uint32 PutObjectInitRequestPro::objectsize() const {
  return objectsize_;
}
inline void PutObjectInitRequestPro::set_objectsize(::google::protobuf::uint32 value) {
  set_has_objectsize();
  objectsize_ = value;
}

// optional fixed32 chunkCount = 3;
inline bool PutObjectInitRequestPro::has_chunkcount() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PutObjectInitRequestPro::set_has_chunkcount() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PutObjectInitRequestPro::clear_has_chunkcount() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PutObjectInitRequestPro::clear_chunkcount() {
  chunkcount_ = 0u;
  clear_has_chunkcount();
}
inline ::google::protobuf::uint32 PutObjectInitRequestPro::chunkcount() const {
  return chunkcount_;
}
inline void PutObjectInitRequestPro::set_chunkcount(::google::protobuf::uint32 value) {
  set_has_chunkcount();
  chunkcount_ = value;
}

// -------------------------------------------------------------------

// ObjectDataPro

// optional fixed64 objectId = 1;
inline bool ObjectDataPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ObjectDataPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ObjectDataPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ObjectDataPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 ObjectDataPro::objectid() const {
  return objectid_;
}
inline void ObjectDataPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed64 offset = 2;
inline bool ObjectDataPro::has_offset() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectDataPro::set_has_offset() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectDataPro::clear_has_offset() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectDataPro::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 ObjectDataPro::offset() const {
  return offset_;
}
inline void ObjectDataPro::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
}

// optional fixed32 length = 3;
inline bool ObjectDataPro::has_length() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ObjectDataPro::set_has_length() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ObjectDataPro::clear_has_length() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ObjectDataPro::clear_length() {
  length_ = 0u;
  clear_has_length();
}
inline ::google::protobuf::uint32 ObjectDataPro::length() const {
  return length_;
}
inline void ObjectDataPro::set_length(::google::protobuf::uint32 value) {
  set_has_length();
  length_ = value;
}

// -------------------------------------------------------------------

// PutObjectEndRequestPro

// optional fixed64 objectId = 1;
inline bool PutObjectEndRequestPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutObjectEndRequestPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutObjectEndRequestPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutObjectEndRequestPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutObjectEndRequestPro::objectid() const {
  return objectid_;
}
inline void PutObjectEndRequestPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// -------------------------------------------------------------------

// PutObjectInitReplyPro

// optional fixed64 objectId = 1;
inline bool PutObjectInitReplyPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutObjectInitReplyPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutObjectInitReplyPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutObjectInitReplyPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutObjectInitReplyPro::objectid() const {
  return objectid_;
}
inline void PutObjectInitReplyPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// -------------------------------------------------------------------

// PutObjectEndReplyPro

// optional fixed64 objectId = 1;
inline bool PutObjectEndReplyPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutObjectEndReplyPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutObjectEndReplyPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutObjectEndReplyPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutObjectEndReplyPro::objectid() const {
  return objectid_;
}
inline void PutObjectEndReplyPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// -------------------------------------------------------------------

// PutSegmentInitRequestPro

// optional fixed64 objectId = 1;
inline bool PutSegmentInitRequestPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutSegmentInitRequestPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutSegmentInitRequestPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutSegmentInitRequestPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutSegmentInitRequestPro::objectid() const {
  return objectid_;
}
inline void PutSegmentInitRequestPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 segmentId = 2;
inline bool PutSegmentInitRequestPro::has_segmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutSegmentInitRequestPro::set_has_segmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutSegmentInitRequestPro::clear_has_segmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutSegmentInitRequestPro::clear_segmentid() {
  segmentid_ = 0u;
  clear_has_segmentid();
}
inline ::google::protobuf::uint32 PutSegmentInitRequestPro::segmentid() const {
  return segmentid_;
}
inline void PutSegmentInitRequestPro::set_segmentid(::google::protobuf::uint32 value) {
  set_has_segmentid();
  segmentid_ = value;
}

// optional fixed32 segmentSize = 3;
inline bool PutSegmentInitRequestPro::has_segmentsize() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PutSegmentInitRequestPro::set_has_segmentsize() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PutSegmentInitRequestPro::clear_has_segmentsize() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PutSegmentInitRequestPro::clear_segmentsize() {
  segmentsize_ = 0u;
  clear_has_segmentsize();
}
inline ::google::protobuf::uint32 PutSegmentInitRequestPro::segmentsize() const {
  return segmentsize_;
}
inline void PutSegmentInitRequestPro::set_segmentsize(::google::protobuf::uint32 value) {
  set_has_segmentsize();
  segmentsize_ = value;
}

// optional fixed32 chunkCount = 4;
inline bool PutSegmentInitRequestPro::has_chunkcount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PutSegmentInitRequestPro::set_has_chunkcount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PutSegmentInitRequestPro::clear_has_chunkcount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PutSegmentInitRequestPro::clear_chunkcount() {
  chunkcount_ = 0u;
  clear_has_chunkcount();
}
inline ::google::protobuf::uint32 PutSegmentInitRequestPro::chunkcount() const {
  return chunkcount_;
}
inline void PutSegmentInitRequestPro::set_chunkcount(::google::protobuf::uint32 value) {
  set_has_chunkcount();
  chunkcount_ = value;
}

// -------------------------------------------------------------------

// SegmentDataPro

// optional fixed64 objectId = 1;
inline bool SegmentDataPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SegmentDataPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SegmentDataPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SegmentDataPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 SegmentDataPro::objectid() const {
  return objectid_;
}
inline void SegmentDataPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 segmentId = 2;
inline bool SegmentDataPro::has_segmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SegmentDataPro::set_has_segmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SegmentDataPro::clear_has_segmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SegmentDataPro::clear_segmentid() {
  segmentid_ = 0u;
  clear_has_segmentid();
}
inline ::google::protobuf::uint32 SegmentDataPro::segmentid() const {
  return segmentid_;
}
inline void SegmentDataPro::set_segmentid(::google::protobuf::uint32 value) {
  set_has_segmentid();
  segmentid_ = value;
}

// optional fixed64 offset = 3;
inline bool SegmentDataPro::has_offset() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SegmentDataPro::set_has_offset() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SegmentDataPro::clear_has_offset() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SegmentDataPro::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 SegmentDataPro::offset() const {
  return offset_;
}
inline void SegmentDataPro::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
}

// optional fixed32 length = 4;
inline bool SegmentDataPro::has_length() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SegmentDataPro::set_has_length() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SegmentDataPro::clear_has_length() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SegmentDataPro::clear_length() {
  length_ = 0u;
  clear_has_length();
}
inline ::google::protobuf::uint32 SegmentDataPro::length() const {
  return length_;
}
inline void SegmentDataPro::set_length(::google::protobuf::uint32 value) {
  set_has_length();
  length_ = value;
}

// -------------------------------------------------------------------

// PutSegmentEndRequestPro

// optional fixed64 objectId = 1;
inline bool PutSegmentEndRequestPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutSegmentEndRequestPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutSegmentEndRequestPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutSegmentEndRequestPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutSegmentEndRequestPro::objectid() const {
  return objectid_;
}
inline void PutSegmentEndRequestPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 segmentId = 2;
inline bool PutSegmentEndRequestPro::has_segmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutSegmentEndRequestPro::set_has_segmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutSegmentEndRequestPro::clear_has_segmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutSegmentEndRequestPro::clear_segmentid() {
  segmentid_ = 0u;
  clear_has_segmentid();
}
inline ::google::protobuf::uint32 PutSegmentEndRequestPro::segmentid() const {
  return segmentid_;
}
inline void PutSegmentEndRequestPro::set_segmentid(::google::protobuf::uint32 value) {
  set_has_segmentid();
  segmentid_ = value;
}

// -------------------------------------------------------------------

// PutSegmentInitReplyPro

// optional fixed64 objectId = 1;
inline bool PutSegmentInitReplyPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutSegmentInitReplyPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutSegmentInitReplyPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutSegmentInitReplyPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutSegmentInitReplyPro::objectid() const {
  return objectid_;
}
inline void PutSegmentInitReplyPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 segmentId = 2;
inline bool PutSegmentInitReplyPro::has_segmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutSegmentInitReplyPro::set_has_segmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutSegmentInitReplyPro::clear_has_segmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutSegmentInitReplyPro::clear_segmentid() {
  segmentid_ = 0u;
  clear_has_segmentid();
}
inline ::google::protobuf::uint32 PutSegmentInitReplyPro::segmentid() const {
  return segmentid_;
}
inline void PutSegmentInitReplyPro::set_segmentid(::google::protobuf::uint32 value) {
  set_has_segmentid();
  segmentid_ = value;
}

// -------------------------------------------------------------------

// PutSegmentEndReplyPro

// optional fixed64 objectId = 1;
inline bool PutSegmentEndReplyPro::has_objectid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PutSegmentEndReplyPro::set_has_objectid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PutSegmentEndReplyPro::clear_has_objectid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PutSegmentEndReplyPro::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
  clear_has_objectid();
}
inline ::google::protobuf::uint64 PutSegmentEndReplyPro::objectid() const {
  return objectid_;
}
inline void PutSegmentEndReplyPro::set_objectid(::google::protobuf::uint64 value) {
  set_has_objectid();
  objectid_ = value;
}

// optional fixed32 segmentId = 2;
inline bool PutSegmentEndReplyPro::has_segmentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PutSegmentEndReplyPro::set_has_segmentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PutSegmentEndReplyPro::clear_has_segmentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PutSegmentEndReplyPro::clear_segmentid() {
  segmentid_ = 0u;
  clear_has_segmentid();
}
inline ::google::protobuf::uint32 PutSegmentEndReplyPro::segmentid() const {
  return segmentid_;
}
inline void PutSegmentEndReplyPro::set_segmentid(::google::protobuf::uint32 value) {
  set_has_segmentid();
  segmentid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ncvfs

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
